// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['backend']['App']['Bootstrap']();
}

export function Branches(arg1) {
  return window['go']['backend']['App']['Branches'](arg1);
}

export function CancelAnalysis(arg1) {
  return window['go']['backend']['App']['CancelAnalysis'](arg1);
}

export function CancelScan(arg1) {
  return window['go']['backend']['App']['CancelScan'](arg1);
}

export function CloneRepository(arg1) {
  return window['go']['backend']['App']['CloneRepository'](arg1);
}

export function Commits(arg1) {
  return window['go']['backend']['App']['Commits'](arg1);
}

export function ConfigPath() {
  return window['go']['backend']['App']['ConfigPath']();
}

export function Linters(arg1) {
  return window['go']['backend']['App']['Linters'](arg1);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['backend']['App']['ListDirectory'](arg1, arg2);
}

export function ListRemoteDirectory(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ListRemoteDirectory'](arg1, arg2, arg3);
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['backend']['App']['OpenInEditor'](arg1, arg2);
}

export function OpenRepositoryOnGitHub(arg1) {
  return window['go']['backend']['App']['OpenRepositoryOnGitHub'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['backend']['App']['OpenURL'](arg1);
}

export function PreloadRemoteRepository(arg1, arg2) {
  return window['go']['backend']['App']['PreloadRemoteRepository'](arg1, arg2);
}

export function PullLatest(arg1) {
  return window['go']['backend']['App']['PullLatest'](arg1);
}

export function PullRequestDetail(arg1, arg2) {
  return window['go']['backend']['App']['PullRequestDetail'](arg1, arg2);
}

export function PullRequests(arg1) {
  return window['go']['backend']['App']['PullRequests'](arg1);
}

export function ReadFile(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ReadFile'](arg1, arg2, arg3);
}

export function ReadOverview(arg1, arg2) {
  return window['go']['backend']['App']['ReadOverview'](arg1, arg2);
}

export function ReadRemoteFile(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ReadRemoteFile'](arg1, arg2, arg3, arg4);
}

export function ReadRemoteOverview(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ReadRemoteOverview'](arg1, arg2, arg3);
}

export function RefreshRepos() {
  return window['go']['backend']['App']['RefreshRepos']();
}

export function RefreshRepository(arg1) {
  return window['go']['backend']['App']['RefreshRepository'](arg1);
}

export function RemoteBranches(arg1) {
  return window['go']['backend']['App']['RemoteBranches'](arg1);
}

export function RepositoryFingerprint(arg1) {
  return window['go']['backend']['App']['RepositoryFingerprint'](arg1);
}

export function RepositorySources() {
  return window['go']['backend']['App']['RepositorySources']();
}

export function RepositoryStats(arg1) {
  return window['go']['backend']['App']['RepositoryStats'](arg1);
}

export function RunLinters(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['RunLinters'](arg1, arg2, arg3, arg4);
}

export function Scanners() {
  return window['go']['backend']['App']['Scanners']();
}

export function SearchRepository(arg1, arg2) {
  return window['go']['backend']['App']['SearchRepository'](arg1, arg2);
}

export function SearchRepositoryFiles(arg1, arg2) {
  return window['go']['backend']['App']['SearchRepositoryFiles'](arg1, arg2);
}

export function SearchRepositoryFilesPattern(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SearchRepositoryFilesPattern'](arg1, arg2, arg3);
}

export function SearchRepositoryPattern(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SearchRepositoryPattern'](arg1, arg2, arg3);
}

export function SelectWorkspace() {
  return window['go']['backend']['App']['SelectWorkspace']();
}

export function StartAnalysis(arg1, arg2, arg3) {
  return window['go']['backend']['App']['StartAnalysis'](arg1, arg2, arg3);
}

export function StartScan(arg1, arg2) {
  return window['go']['backend']['App']['StartScan'](arg1, arg2);
}

export function SubmitPullRequestReview(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['SubmitPullRequestReview'](arg1, arg2, arg3, arg4);
}

export function SwitchBranch(arg1, arg2) {
  return window['go']['backend']['App']['SwitchBranch'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['backend']['App']['UpdateConfig'](arg1);
}
