// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Bootstrap():Promise<backend.Bootstrap>;

export function Branches(arg1:string):Promise<Array<string>>;

export function CancelAnalysis(arg1:string):Promise<void>;

export function CancelScan(arg1:string):Promise<void>;

export function CloneRepository(arg1:string):Promise<backend.Repo>;

export function Commits(arg1:string):Promise<Array<backend.Commit>>;

export function ConfigPath():Promise<string>;

export function GitIdentity(arg1:string):Promise<backend.GitIdentity>;

export function Linters(arg1:string):Promise<Array<backend.LinterInfo>>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<backend.TreeEntry>>;

export function ListRemoteDirectory(arg1:string,arg2:string,arg3:string):Promise<Array<backend.TreeEntry>>;

export function OpenInEditor(arg1:string,arg2:string):Promise<void>;

export function OpenRepositoryOnGitHub(arg1:backend.Repo):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PreloadRemoteRepository(arg1:string,arg2:string):Promise<number>;

export function PullLatest(arg1:string):Promise<string>;

export function PullRequestDetail(arg1:string,arg2:number):Promise<backend.PullRequestDetail>;

export function PullRequests(arg1:string):Promise<Array<backend.PullRequest>>;

export function ReadFile(arg1:string,arg2:string,arg3:string):Promise<backend.Document>;

export function ReadOverview(arg1:string,arg2:string):Promise<backend.Document>;

export function ReadRemoteFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<backend.Document>;

export function ReadRemoteOverview(arg1:string,arg2:string,arg3:string):Promise<backend.Document>;

export function RefreshRepos():Promise<Array<backend.Repo>>;

export function RefreshRepository(arg1:string):Promise<void>;

export function RemoteBranches(arg1:string):Promise<Array<string>>;

export function RepositoryFingerprint(arg1:string):Promise<string>;

export function RepositorySources():Promise<backend.RepositorySources>;

export function RepositoryStats(arg1:string):Promise<backend.RepositoryStats>;

export function RunLinters(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<Array<backend.LintReport>>;

export function Scanners():Promise<Array<backend.ScannerInfo>>;

export function SearchRepository(arg1:string,arg2:string):Promise<Array<backend.SearchResult>>;

export function SearchRepositoryFiles(arg1:string,arg2:string):Promise<Array<backend.SearchResult>>;

export function SearchRepositoryFilesPattern(arg1:string,arg2:string,arg3:boolean):Promise<Array<backend.SearchResult>>;

export function SearchRepositoryPattern(arg1:string,arg2:string,arg3:boolean):Promise<Array<backend.SearchResult>>;

export function SelectWorkspace():Promise<string>;

export function StartAnalysis(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartScan(arg1:string,arg2:string):Promise<string>;

export function SubmitPullRequestReview(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SwitchBranch(arg1:string,arg2:string):Promise<string>;

export function UpdateConfig(arg1:backend.Config):Promise<backend.Bootstrap>;
