// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Bootstrap():Promise<main.Bootstrap>;

export function Branches(arg1:string):Promise<Array<string>>;

export function CancelAnalysis(arg1:string):Promise<void>;

export function CancelScan(arg1:string):Promise<void>;

export function CloneRepository(arg1:string):Promise<main.Repo>;

export function Commits(arg1:string):Promise<Array<main.Commit>>;

export function ConfigPath():Promise<string>;

export function Linters(arg1:string):Promise<Array<main.LinterInfo>>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<main.TreeEntry>>;

export function OpenInEditor(arg1:string,arg2:string):Promise<void>;

export function OpenRepositoryOnGitHub(arg1:main.Repo):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PullLatest(arg1:string):Promise<string>;

export function PullRequests(arg1:string):Promise<Array<main.PullRequest>>;

export function ReadFile(arg1:string,arg2:string,arg3:string):Promise<main.Document>;

export function ReadOverview(arg1:string,arg2:string):Promise<main.Document>;

export function RefreshRepos():Promise<Array<main.Repo>>;

export function RepositorySources():Promise<main.RepositorySources>;

export function RepositoryStats(arg1:string):Promise<main.RepositoryStats>;

export function RunLinters(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<Array<main.LintReport>>;

export function Scanners():Promise<Array<main.ScannerInfo>>;

export function SearchRepository(arg1:string,arg2:string):Promise<Array<main.SearchResult>>;

export function SearchRepositoryFiles(arg1:string,arg2:string):Promise<Array<main.SearchResult>>;

export function SearchRepositoryFilesPattern(arg1:string,arg2:string,arg3:boolean):Promise<Array<main.SearchResult>>;

export function SearchRepositoryPattern(arg1:string,arg2:string,arg3:boolean):Promise<Array<main.SearchResult>>;

export function SelectWorkspace():Promise<string>;

export function StartAnalysis(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartScan(arg1:string,arg2:string):Promise<string>;

export function SwitchBranch(arg1:string,arg2:string):Promise<string>;

export function UpdateConfig(arg1:main.Config):Promise<main.Bootstrap>;
