// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function Branches(arg1) {
  return window['go']['main']['App']['Branches'](arg1);
}

export function CancelAnalysis(arg1) {
  return window['go']['main']['App']['CancelAnalysis'](arg1);
}

export function CancelScan(arg1) {
  return window['go']['main']['App']['CancelScan'](arg1);
}

export function CloneRepository(arg1) {
  return window['go']['main']['App']['CloneRepository'](arg1);
}

export function Commits(arg1) {
  return window['go']['main']['App']['Commits'](arg1);
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function ListDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2);
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditor'](arg1, arg2);
}

export function OpenRepositoryOnGitHub(arg1) {
  return window['go']['main']['App']['OpenRepositoryOnGitHub'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PullRequests(arg1) {
  return window['go']['main']['App']['PullRequests'](arg1);
}

export function ReadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2, arg3);
}

export function ReadOverview(arg1, arg2) {
  return window['go']['main']['App']['ReadOverview'](arg1, arg2);
}

export function RefreshRepos() {
  return window['go']['main']['App']['RefreshRepos']();
}

export function RepositoryStats(arg1) {
  return window['go']['main']['App']['RepositoryStats'](arg1);
}

export function Scanners() {
  return window['go']['main']['App']['Scanners']();
}

export function SearchRepository(arg1, arg2) {
  return window['go']['main']['App']['SearchRepository'](arg1, arg2);
}

export function SearchRepositoryFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchRepositoryFiles'](arg1, arg2);
}

export function StartAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAnalysis'](arg1, arg2, arg3);
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}

export function SwitchBranch(arg1, arg2) {
  return window['go']['main']['App']['SwitchBranch'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
